services:
  mysql:
    image: mysql:8.4
    container_name: recipebot-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: recipebot
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    command: ["--character-set-server=utf8mb4", "--collation-server=utf8mb4_general_ci"]
    volumes:
      - ./mysql_data:/var/lib/mysql
